
logging:
  outputLevel: "info"

# Chain network configuration
chain:
  displayName: "Test Chain"

# HTTP Server configuration
server:
  host: "0.0.0.0" # Address to listen on
  port: "8088" # Port to listen on

frontend:
  enabled: true # Enable or disable to web frontend
  debug: false
  pprof: true
  minimize: false # minimize html templates
  disablePageCache: true
  showSensitivePeerInfos: true

  # Name of the site, displayed in the title tag
  siteName: "Dora the Explorer"
  siteSubtitle: "yourchain  - YourChain"

  # link to EL Explorer
  ethExplorerLink: ""

  # file or inventory url to load validator names from
  validatorNamesYaml: "/validator-ranges/validator-ranges.yaml"

  publicRpcUrl: "http://your_ip:8545"
  rainbowkitProjectId: "15fe4ab4d5c0bcb6f0dc7c398301ff0e"
  showSubmitDeposit: true
  showSubmitElRequests: true

beaconapi:
  # CL Client RPC
  endpoints:

    - url: "http://your_ip:5052"
      name: "1-geth-lighthouse"
      archive: true
  # local cache for page models
  localCacheSize: 10 # 10MB

  # remote cache for page models
  redisCacheAddr: ""
  redisCachePrefix: ""

executionapi:
  endpoints:

    - url: "http://your_ip:8545"
      name: "1-geth-prysm"
      archive: true
  depositLogBatchSize: 1000

# indexer keeps track of the latest epochs in memory.
indexer:
  # max number of epochs to keep in memory
  inMemoryEpochs: 8

  # disable synchronizing historic data
  disableSynchronizer: false

  # reset synchronization state to this epoch on startup - only use to resync database, comment out afterwards
  #resyncFromEpoch: 0

  # force re-synchronization of epochs that are already present in DB - only use to fix missing data after schema upgrades
  #resyncForceUpdate: true

  # number of seconds to pause the synchronization between each epoch (don't overload CL client)
  syncEpochCooldown: 1

  # maximum number of parallel beacon state requests (might cause high memory usage)
  maxParallelValidatorSetRequests: 2

mevIndexer:
  # list of mev relays to crawl mev blocks from
  relays: []

  refreshInterval: 5m

database:
  engine: "sqlite"
  sqlite:
    file: "/dora-database.sqlite"